# Generated by Django 4.2.9 on 2024-02-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
                ('finish', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(default='normal', max_length=50)),
                ('duration', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
            },
        ),
    ]
