# Generated by Django 4.2.9 on 2024-02-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTaches', '0002_taches_finish_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='duration',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taches',
            name='priority',
            field=models.CharField(default='low', max_length=50),
        ),
    ]
